### ISSUE TITLE
Vue Devtools stuck on vue logo. Error: Toasty Text is not set.

### ISSUE THREAD

**Issue by jadedigital** [nativescript-vue/nativescript-vue-devtools#16]
I'm trying to run vue devtools. After I have it running and waiting for connection, I do `tns run android` and it seems like it almost is about to load my components, but instead the devtools window just shows a vue logo in the middle of the window. Th console gives the following error:

    [Error: Toasty Text is not set.]

**Comment by jadedigital** [comment]
Managed to fix this by uninstalling vue devtools and reinstalling

**Comment by jadedigital** [comment]
I spoke to soon. It connects, but disconnects fairly quickly with that same error:

    [Error: Toasty Text is not set.]

**Comment by jadedigital** [comment]
More context, I'm using: 
Windows 10
vue v2.6.10
ns-vue v2.4.0
@vue/devtools v5.3.3
nativescript-vue-devtools v1.2.0


I rolled back from @vue/devtools version 5.3.3 to version 5.1.1
This seems to get it working, but it's also annoying because you cant run using the `vue-devtools` command, instead I have to do the following to get vue devtools to run in windows:

start server
    > node %appdata%\npm\node_modules\@vue\devtools\server.js
start desktop app
    > %appdata%\npm\node_modules\@vue\devtools\node_modules\electron\dist\electron.exe 
    %appdata%\npm\node_modules\@vue\devtools\app.html

**Comment by rigor789** [comment]
Released `1.3.0` that uses the new Toasty api (>= 2.0). 

Tested with `nativescript-toasty@3.0.0-alpha.2`.
