### ISSUE TITLE
Nothing happens when I run npx vue-devtools

### ISSUE THREAD

**Issue by andresilva-cc** [nativescript-vue/nativescript-vue-devtools#17]
I'm following the [official documentation](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/).
When I type `npx vue-devtools` in my project folder, nothing happens, no error returned, nothing.

I also tried a new project, nothing happens too...

**package.json:**
```json
"dependencies": {
    "@vue/devtools": "^5.3.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "nativescript-vue": "~2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "~6.1.0",
    "vue-i18n": "^8.17.0"
  },
"devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.2.0",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  }
```

**app.js:**
```javascript
import VueDevtools from 'nativescript-vue-devtools'
import Vue from 'nativescript-vue'
import i18n from './assets/lang'

// Pages
import WelcomePage from './pages/Welcome'

Vue.use(VueDevtools)

// Load plugins
require('./plugins')

// Load filters
require('./utils/filters')

new Vue({

    template: `
        <Frame>
            <WelcomePage />
        </Frame>`,

    components: {
        WelcomePage
    },

    i18n
}).$start()

```
**System info:**
**OS:** Debian 10.3 Buster
**Node.js:** v.10.20.1
**npm:** 6.14.4
**npx:** 6.14.4

**Comment by rigor789** [comment]
That's odd - have you ran `npm install`? Check `node_modules/bin` folder and see if there is a `vue-devtools` file.

Another thing you can try is to just run `npx @vue/devtools` instead.

**Comment by andresilva-cc** [comment]
Yes, I have run `npm install`.
There's no `bin` folder inside `node_modules`.

`npx @vue/devtools` happens nothing too...

**Comment by rigor789** [comment]
Try running the bin directly with `node node_modules/.bin/vue-devtools` (or whatever the path/filename is) and see if there are any errors. 

Could be something with your setup, I'm not sure. The command should open an electron window with the devtools.

If it's not working, try looking for issues in the Vue Devtools repo: https://github.com/vuejs/vue-devtools/issues

This repo only contains the code required to connect to the devtools from a NativeScript-Vue app.

**Comment by andresilva-cc** [comment]
I also tried this before but no luck, still nothing opens.

Good idea, I'm gonna search (or post if I don't find anything) in the DevTools repo. For now, I'll leave this issue on standby.

**Comment by andresilva-cc** [comment]
I found the issue and found a possible solution that didn't work for me, so I posted a new comment there.
If anyone wants to read it, go to https://github.com/vuejs/vue-devtools/issues/1071#issuecomment-613643158

For now, I'm going to close this issue as it isn't a problem with `nativescript-vue-devtools`, but with `vue-devtools`.

Thank's @rigor789 for the help.

**Comment by rigor789** [comment]
Hope you figure it out soon!
